name: Publish in Microsoft Marketplace
run-name: ${{ github.triggering_actor }} is publishing in Microsoft Marketplace from ${{ github.ref_name }}
on:
  workflow_dispatch: #  Button for publishing from input branch in case there is a failure on the release.

jobs:
  publish-start-notification:
    name: 'Publish Einstein for Developers in MS Marketplace Start Notification'
    uses: ./.github/workflows/slackNotification.yml
    secrets: inherit
    with:
      title: 'Publish Einstein for Developers in MS Marketplace waiting for approval in github.'
      notification: 'New Release triggered publish build and job is ready for approval.'
      type: 'notification'
      workflow: 'publishVSCode.yml'
  get-release-version:
    uses: ./.github/workflows/getReleaseVersion.yml
    secrets: inherit
  output-release-version:
    runs-on: ubuntu-latest
    needs: [get-release-version]
    steps:
      - run: echo "Publishing version ${{ needs.get-release-version.outputs.release-version }}"
  publish:
    needs: [get-release-version]
    runs-on: ubuntu-latest
    env:
      VSCE_PERSONAL_ACCESS_TOKEN: ${{ secrets.VSCE_PERSONAL_ACCESS_TOKEN }}
      PUBLISH_VERSION: ${{ needs.get-release-version.outputs.release-version }}
      GITHUB_TOKEN: ${{ secrets.IDEE_GH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          token: ${{ secrets.IDEE_GH_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: downloadExtensionsFromRelease
        run: |
          mkdir ./extensions
          gh release download v${{ env.PUBLISH_VERSION }} -D ./extensions
      - name: Display downloaded vsix files
        run: ls -R ./extensions
      - name: Configure Git for private repo access
        run: git config --global --add url."https://${{ secrets.IDEE_GH_TOKEN }}@github.com/".insteadOf "https://github.com/"
      - run: npm ci
      - run: find ./extensions -type f -name "salesforcedx-einstein-gpt*.vsix" -exec npx vsce publish --pat ${{ env.VSCE_PERSONAL_ACCESS_TOKEN }} --packagePath {} \;
      - run: echo "SUCCESSFULLY published"
